language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: NPHjSHhH+KR5gGNGKA4UvzuXiTGYCAzm+YtkGtB+WzKv777R63EKLuCTuvNAYqOU2DO8e4y/M9+raIP6RdEJ5/OQbtEoZr2n0++eouTdR8FyP2Y/oMXI5ZIS7uHOAb51zsSoe0lkWUoGOmyIlbOWEd6qcjQSFyy87C8FgF2ugHu6mckKSdmUSNDzwlsDtAO5gytTFZ+jHaLwdDpR895G6xh1cExvIswVRJYqc/U8Re+r/MNzb+tWwCNT/kDd3E6kjYRJQ523SkRGLrVt2M8Kfa/erUFTJvbBYcuZt1B3kfr8SUZlMiydifnfiT82Pe4360OJJv+NEnReIVFSopmiKofFXLEbbE6G1EkptUHptl6zN4gELnyZ6XjUcxbDJLRliaTxvUUtcY70PcSPG0X9KaMAkRbz6Nm8peceuH/9dSCoW7klQTILfPiptmd772W+BbdYXSIlDDUsBVp18aSbKOsql9IxsC/9GUMmGMI8TcF5izvaeSbvJuBlAqVBqpGiXzRoof9hSEX3HRCRGpbjy+EcrD/YT45te2/YYiXQWSSzmGrXPmJNWBiC3SFaU294eCv1bAda0it+yCkrHL4TiBjsNOSKSsk5lf+lDu18X/KdjHTN6CfB2KJC7+Mf1XBlbGT+FwmyaooWbDd7APUxnjXECC3JVvhHzQXIWcUqMDM=
  app: calm-chamber-19158
  on:
    repo: rrabinovitch/viewing_party
    branch: main
  skip_cleanup: 'true'
  run: rails db:migrate
env:
  global:
    secure: hrFkr4WJTXdJCBKUH8+vPjLDPJ0ohwF5kwsYf23q6xsCMAyaacRDVA40QQOtUWAWh1UDccb/njLEAS+v7pgb1Xpuh5dVpp6k2xxIASz/UhyJ308QkxQkigmSBmMVyk6wWAE9/xJcHHRYaTR9uX2yFLRZLbN5n//EEPxXu13UpemZ3gWIiC8E9MR8s9YpA/3JkgPJIEbCWWaVe/9YdeiFymZvNrSP9t+M4wMYmXuUUbVjoSVn7NR8Uek2A/M1MNiQQwheefWNip6Me1k8oOFqyTHYG7VvQzaHeoZcCt/bgjOWeJcQ1FDThBAh3i14QBgtMQ5KjUdbtQ3gw3wkR1YtjqoCMKj32WBP3IKgSNHopxb815yM70/2jZoNkf8/2gcI4cGuiHq0FU81HBFK3Y5nXr3d/XVfGNmMgzvL7moDbFrjBb5oLnBOFiWADEnsdfVJkcCqKq86n2f8VrlTf38+B/DtlTKISzIRatp+O2qNYR0CVw+iqsXJmC7+PWmuisceBRTxgwRRfIxZxUuG9FMggPaiiT94WQjV/f6PJlr1P5UM/NUlixLknOJIhCsjsIROrC7oaxv2GrTByAGZGrd8A++w09P3E6z+sj2pgfeVEev9f/Qq9QqUMVD80L/a/TnUC2XF+/XozVaeUZ3qgAMczRIQCGqCcTWvuMm5VLjjkBo=
